name: Kubernv1 cli

on:
  label:
    types:
      - created

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: arcv1.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        sudo docker build . -t arcv1.azurecr.io/myapp:${{ github.sha }}
        sudo docker push arcv1.azurecr.io/myapp:${{ github.sha }}
